# Generated by Django 4.1.3 on 2022-11-22 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='temp_img/', verbose_name='img')),
            ],
            options={
                'db_table': 'temp_img',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_contact', models.BigIntegerField()),
                ('user_password', models.CharField(max_length=50)),
                ('user_license', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='media/')),
                ('user_status', models.CharField(default='pending', max_length=50)),
                ('user_email_status', models.CharField(blank=True, max_length=50, null=True)),
                ('user_sms_status', models.CharField(blank=True, max_length=50, null=True)),
                ('user_call_status', models.CharField(blank=True, max_length=50, null=True)),
                ('user_privacy_status', models.CharField(max_length=50)),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
