# Generated by Django 4.1.3 on 2022-11-24 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionModel',
            fields=[
                ('interac_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500, null=True)),
                ('interac_type', models.CharField(max_length=50, null=True)),
                ('datetime_sent', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='mainapp.usermodel')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'interactions_details',
            },
        ),
    ]
