# Generated by Django 4.1.3 on 2022-11-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=500, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('datetime_reviewed', models.DateTimeField(auto_now=True)),
                ('reviewee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='mainapp.usermodel')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'user_feedbacks',
            },
        ),
    ]
