# Generated by Django 4.1.3 on 2022-11-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='sentinent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
