# Generated by Django 4.1.3 on 2022-12-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_feedbackmodel_sentinent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='sentinent',
            new_name='sentiment',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='reviewee',
        ),
    ]
